name: 'Deployment'

on:
  pull_request:

jobs:
  cluster-app:
    name: 'Deployment'
    runs-on: ubuntu-latest
    steps:
     # Checkout the repository to the GitHub Actions runner
     # Setup gcloud CLI
       - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
         with:
           service_account_key: ${{ secrets.GKE_SA_KEY }}
           project_id: ${{ secrets.GCP_PROJECT_ID }}

       # Configure Docker to use the gcloud command-line tool as a credential
       # helper for authentication
       - run: |-
           gcloud --quiet auth configure-docker

       # Get the GKE credentials so we can deploy to the cluster
       - run: |-
           gcloud container clusters get-credentials terra-cluster --zone us-central1

