name: 'Deployment'

on:
  pull_request:

jobs:
  cluster-app:
    name: 'Deployment'
    runs-on: ubuntu-latest
    steps:
      - name: GCR
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Docker Build
        run: |
          docker build -t gcr.io/int-project/temp
          docker push gcr.io/int-project/temp

