name: 'Deployment'

on:
  pull_request:
    paths:
      - Temp-Converter/*

jobs:
  cluster-app:
    name: 'Deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cluster
        uses: shashank0202/docker-build-push-gcr-update-gke-deployment-action@1.4
        with:
          working-directory: Temp-Converter
          service_account: ${{ secrets.GCLOUD_AUTH}}
          zone: 'us-central1'
          project_id: ${{ secrets.GCP_PROJECT_ID}}
          registry: 'us.gcr.io'
          image_name: 'dev-tf'
          cluster: 'terra-cluster'
          namespace: 'temp-convert'
          deployment: 'front-end-dep'
          container: 'temp-convert'
