name: 'Terraform GitHub Actions'
on:
  pull_request:

jobs:
  terraform:
    name: 'Terraform-Plan'
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        id: checkout_code
        uses: actions/checkout@v2

      - name: configure gcloud
        id: config_gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "latest"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: false

      - name: set GCP project
        id: config_project
        run: gcloud config set project int-project

# Downloads a specific version of Terraform CLI and adds it to PATH
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1

      # Init pulls credentials from the .aws/credentials file by default
      # -input = false will not require an input
      - name: "Run - Terraform Init"
        run: terraform init -input=false
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}
      # The id value is used for reference in the comment step via "steps.plan.outputs.stdout"
      # Note: Color is disabled to prevent messy characters from appearing in the pull request comment
      # -no-color Disables terminal formatting sequences in the output
      - name: "Run - Terraform Plan"
        id: plan
        run: terraform plan -input=false -no-color
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}

#      - name: "Terraform Plan"
#        id: terraform_plan
#        uses: ops18/terraform-github-actions@master
#        with:
#          tf_actions_subcommand: plan
#        env:
#          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}

#      - name: "Terraform Apply"
#        uses: ops18/terraform-github-actions@master
#        id: terraform_apply
#        with:
#          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
#          tf_actions_comment: "false"
#          tf_actions_working_dir: environments/${{ env.BRANCH_NAME }}
#          tf_actions_subcommand: apply
#        env:
#          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}